### PR TITLE
[SAM] fixes/adjustments

### LINKED ISSUE #1767: [SAM] Kenki Overcapping during the 2 min
Hello! Thank you all for all teh good work!

a) I am having an issue with samurai overcapping during the 2 min burst phase.
I believe its because Zanshin is not being used at the proper time, so it leads to overcapping.

My GCD is at 2.13, which could be causing this, i dont know if this version of samurai is made for a specific skill speed tier.

b) Higanbana also does not refresh in time, causing the target to stay without the dot for some seconds, which again, could be because of my skill speed. This issue happens before the 2 min burst.

### LINKED ISSUE #1780: Samurai Feature 40: Laijutsu to Tsubame-Gaeshi
As far as I can tell this ones not working, tested on lvl 100 against a dummy.

### LINKED ISSUE #1789: [SAM]
First time using github and report any sort of issue, I hope I'm clear.

As others have reported, Simple or Advanced Single Target Modes do not use Shinten or Zanshin when Zanshin is available, leading to overcapping on Kenki.

Higanbana will be used even if you set the 'Do Not Use', regardless of threshold with the Advanced Single Target Mode.

### PR DESCRIPTION
**Pull request by Akechi-kun**
fixes #1708 
fixes #1767 
fixes #1780
fixes #1789 

- [x] Rework rotation to fit 2.14 Optimal standards, per the Balance
- [x] Remove _Tsubame-gaeshi_ from **JobHelpers.cs** (not needed)
- [x] Add _Tsubame-gaeshi_ back into **SAM.cs** 
- [x] Add optimal conditions to _Tsubame-gaeshi_
- [x] Add optimal conditions to _MeikyoShisui_
- [x] Add overcap protection for _MeikyoShisui_ (in case of scuffed runs) 
- [x] _6-minute_ burst fixes (also fixes our rotation loop)
- [x] Fix issue with _Iaijutsu to Tsubame-gaeshi_ option not calling regardless of setting in _Iaijutsu Features_

### CODE REVIEW

File: XIVSlothCombo/Combos/PvE/SAM.cs [hunk 1]
```diff
@@ -215,26 +213,15 @@ internal class SAM_ST_SimpleMode : CustomCombo
...
+                bool threeSen = OriginalHook(Iaijutsu) is MidareSetsugekka or TendoSetsugekka;
                 float enemyHP = GetTargetHPPercent();
                 bool trueNorthReady = TargetNeedsPositionals() && ActionReady(All.TrueNorth) && !HasEffect(All.Buffs.TrueNorth) && CanDelayedWeave(actionID);
-                float meikyostacks = GetBuffStacks(Buffs.MeikyoShisui);
-                
+                float GCD = GetCooldown(Hakaze).CooldownTotal;
+
                 if (actionID is Hakaze or Gyofu)
                 {
-                    if (IsEnabled(CustomComboPreset.SAM_Variant_Cure) &&
```
Comment (Tartarga) [inline XIVSlothCombo/Combos/PvE/SAM.cs:227]: Was the removal of Variant actions in Simple Mode by design? It's in the Adv Single, and both Simple/Adv AoE.

Comment (Akechi-kun) [reply XIVSlothCombo/Combos/PvE/SAM.cs:227]: Yes, however if it's recommended to keep them inside of Simple Mode as well I can add them back.
