### PR TITLE
[GNB] fixes/adjustments

### LINKED ISSUE #1783: [GNB] Low level AoE rotation
Edited to GNB AoE settings:

When doing any low level dungeon anything below 72 (Fated Circle available above 72) the AoE rotation includes Burst Strike in its rotation. Not very good when pulling 2-3 pack of mobs and trying AoE them down while sprinting to the next pack and missing some mobs on pull only to lose enmity.

Here is my AoE settings turned on:
image

### PR DESCRIPTION
**Pull request by Akechi-kun**
closes #1783 
- [x] Add **HP%** slider option to _NoMercy_
- [x] Add _BurstStrike_ option for _AoE_
- [x] Add _BurstStrike Overcap_ option for _AoE_
- [x] Add _Ammo Overcap_ option for _ST_
- [x] Fix issue with burst windows spazzing if _GnashingFang_ was delayed
- [x] Fix issue with burst windows spazzing if _DoubleDown_ was delayed
- [x] Fix issue with _ReignCombo_ not being called if force-disengaged during burst
- [x] Menu cleanup

### CODE REVIEW

File: XIVSlothCombo/Combos/CustomComboPreset.cs [hunk 1]
```diff
@@ -1481,108 +1481,118 @@ public enum CustomComboPreset
...
-        [CustomComboInfo("No Mercy Option", "Adds No Mercy to the main combo when at full ammo.", GNB.JobID)]
-        GNB_ST_NoMercy = 7008,
+        [CustomComboInfo("No Mercy Option", "Adds No Mercy into the rotation when appropriate.", GNB.JobID)]
+        GNB_ST_NoMercy = 7005,
 
         [ParentCombo(GNB_ST_Advanced_CooldownsGroup)]
-        [CustomComboInfo("Danger/Blasting Zone Option", "Adds Danger/Blasting Zone to the main combo.", GNB.JobID)]
-        GNB_ST_BlastingZone = 7009,
+        [CustomComboInfo("Sonic Break Option", "Adds Sonic Break into the rotation when appropriate.", GNB.JobID)]
+        GNB_ST_SonicBreak = 7006,
```
Comment (zbee) [inline XIVSlothCombo/Combos/CustomComboPreset.cs:1499]: These (and many other options aside from those highlighted) should be re-ordered with `CustomComboInfo`'s `Order` parameter, instead of changing the meaning of users' currently selected option IDs.
e.g. If I have `Lightning Shot Uptime` enabled now then after this update I would have `Cooldowns Option` enabled without ever having turned it on.

Comment (zbee) [reply XIVSlothCombo/Combos/CustomComboPreset.cs:1499]: Opened [a PR](https://github.com/Akechi-kun/XIVSlothCombo/pull/15) to keep existing IDs, reordering just by location in file.
